fpw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_website.urls')),
]

my_website/urls.py
from django.urls import path
from my_website import views

app_name = "my_website"

urlpatterns = [
    path('', views.index, name="index"),
    path('skills', views.skills, name="skills"),
    path('contact', views.contact, name="contact"),
    path('about', views.about, name="about"),
    path('work', views.work, name="work"),
    path('<int:pk>', views.project_details, name="project_details"),
]

my_website/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    short_description = models.CharField(max_length=280)
    long_description = models.TextField()
    technology = models.CharField(max_length=150)
    image = models.CharField(max_length=100)
    github_link = models.URLField(max_length=200, default="https://github.com/foorast")

my_website/views.py
from django.shortcuts import render
from my_website.models import Project
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'my_website/index.html')


def skills(request):
    return render(request, 'my_website/skills.html')


def contact(request):
    return render(request, 'my_website/contact.html')


def about(request):
    return render(request, 'my_website/about.html')


def work(request):
    # query the database to return all projects objects
    projects = Project.objects.all()
    return render(request, 'my_website/work.html', {'projects': projects})


def project_details(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'my_website/details.html', {'project': project})

my_website/templates/my_website/about.html
{% extends 'my_website/base.html' %}

{% load static %}

{% block content %}

<main class="l-main">
    <!--===== ABOUT =====-->
    <section class="about section " id="about">
        <h2 class="section-title">About</h2>

        <div class="about__container bd-grid">
            <div id="gallery" class="about__img">
                <img src="{% static 'my_website/img/Fam_h.jpg' %}" alt="">
            </div>

            <div>
                <h2 class="about__subtitle">Hi, I'm Forrest.</h2>
                <p class="about__text">
                    I am a <i>Magna Cum Laude</i> graduate from the University of Massachusetts Lowell where I recieved my B.S. in Information Technology (focus Programming).
                    <br><br>For me programming has always been fulfilling, even when it's frustrating, and that can be often. It's the triumphs over these moments that make it so wonderful though. There is no greater feeling than working your way through the good and the bad until you come out on top with a finished product that you contributed to.
                    <br><br>I truly am a geek at heart after all. I spend my free times working on personal projects, reading and writing fantasy/scifi, playing D&D, really just about any sterotypical nerd stuff. However, I'm also very much a jock because of the +10 years I played Football and other team sports. Often I'll find myself coding my current project with the game on in the background. I guess I'm the weird combination of Geek and Jock.
                    <br><br>Since I'm a new developer I hope to build upon my knowledge and gain expeirence and really fill out this site with accomplishments.
                </p>
                </div>
        </div>
    </section>
</main>

{% endblock %}

my_website/templates/my_website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'my_website/styles.css' %}">
    <link rel="stylesheet" href="{% static 'my_website/JS/sm-core-css.css' %}">
    <link rel="stylesheet" href="{% static 'my_website/JS/sm-clean.css' %}">

    <title>Forrest Walker - Portfolio</title>

    <script src="{% static 'my_website/JS/jquery.min.js' %}"></script>
    <script src="{% static 'my_website/JS/jquery.smartmenus.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('.sm').smartmenus({
                showFunction: function($ul, complete){
                    $ul.slideDown(250, complete);
                },
                hideFunction: function($ul, complete){
                    $ul.slideUp(250, complete);
                }
            }); // end smartmenus
        }); // end ready
    </script>
    <script>
        $(document).ready(function(){
            $('form').submit(function() {
                alert("Your message has been sent.");
            }); // end submit
        }); // end ready
    </script>

</head>
<body>
    <!--===== HEADER =====-->
    <header class="l-header">
        <nav class="nav bd-grid">
            <div>
                <a href="{% url 'my_website:index' %}" class="nav__logo">Forrest</a>
            </div>

            <div class="nav__menu" id="nav-menu">
                <ul class="sm sm-clean">
                    <li class="nav__item"><a href="{% url 'my_website:index' %}" class="nav__link active">Home</a></li>
                    <li class="nav__item"><a href="{% url 'my_website:about' %}" class="nav__link">About</a></li>
                    <li class="nav__item"><a href="{% url 'my_website:skills' %}" class="nav__link">Skills</a></li>
                    <li class="nav__item"><a href="{% url 'my_website:work' %}" class="nav__link">Work</a></li>
                    <li class="nav__item"><a href="#" class="nav__link">Contact</a>
                        <ul>
                            <li class="nav__item"><a href="{% url 'my_website:contact' %}">Contact Form</a></li>
                            <li class="nav__item"><a href="{% static 'my_website/img/WebsiteResume.pdf' %}" download>Resume - Download</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="nav__toggle" id="nav-toggle">
                <i class='bx bx-menu'></i>
            </div>
        </nav>
    </header>
    {% block content %}

    {% endblock %}

    <footer class="footer">
            <p class="footer__title">Forrest</p>
    </footer>
</body>
</html>

my_website/templates/my_website/contact.html
{% extends 'my_website/base.html' %}

{% load static %}

{% block content %}

<main class="l-main">
    <?php if (!empty($msg)) {
        echo "<h2>$msg</h2>";
    } ?>
    <!--===== CONTACT =====-->
    <section class="contact section" id="contact">
        <h2 class="section-title">Contact</h2>

        <div class="contact__container bd-grid">
            <iframe name="votar" style="display: none;"></iframe>
            <form method="POST" class="contact__form" name="contact" id="contact" action="{% static 'my_website/contactForm.php' %}" target="votar">
                <input type="text" name="name" id="name" placeholder="Name" class="contact__input" required>

                <input type="email" name="email" id="email" placeholder="Email" class="contact__input" required>

                <textarea name="message" id="textarea" cols="0" rows="10" class="contact__input" required></textarea>

                <input type="submit" value="Submit" class="contact__button button" name="submit" id="submit">
                <input type="hidden" name="hidePageLoad" value="2">
            </form>
        </div>
    </section>
</main>

{% endblock %}

my_website/templates/my_website/details.html
{% extends 'my_website/base.html' %}

{% load static %}

{% block content %}

<main class="l-main">
    <section class="details section" id="details">
        <h2 class="section-title">Project Details</h2>
        <div class="details__container bd-grid">
            <div>
                <h1 class="details_title">{{ project.title}}</h1>
                <img src="{% static project.image %}" alt="project image">
            </div>
            <div>
                <h2 class="details_title">Technologies</h2>
                <br>
                <p class="details_title">{{ project.technology}}</p>
                <br>
                <h2 class="details_title">GitHub</h2>
                <br>
                <div class="details_title">
                    <a href="{{ project.github_link }}" class="button">Project GitHub</a>
                </div>
                <br><br>
                <h2 class="details_title">Description</h2>
                <br>
                <p class="details_title">{{ project.long_description}}</p>
            </div>
        </div>
    </section>
</main>


{% endblock %}

my_website/templates/my_website/index.html
{% extends 'my_website/base.html' %}

{% load static %}

{% block content %}

<main class="l-main">
    <!--===== HOME =====-->
    <section class="home bd-grid" id="home">
        <div class="home__data">
            <h1 class="home__title">Hi,<br>I am <span class="home__title-color">Forrest</span> a<br>Software Engineer</h1>

            <a href="{% url 'my_website:contact' %}" class="button">Contact</a>
        </div>

        <div class="home__social">
            <a href="" class="home__social-icon"><i class='bx bxl-linkedin'></i></a>
            <a href="" class="home__social-icon"><i class='bx bxl-github' ></i></a>
        </div>

    </section>
</main>

{% endblock %}

my_website/templates/my_website/skills.html
{% extends 'my_website/base.html' %}

{% load static %}

{% block content %}

<main class="l-main">
    <!--===== SKILLS =====-->
    <section class="skills section" id="skills">
        <h2 class="section-title">Skills</h2>

        <div class="skills__container bd-grid">
            <div>
                <h2 class="skills__subtitle">Professional Skills</h2>
                <p class="skills__text">
                    These represent my confidence level in my skills with the following languages.
                </p>
                <div class="skills__data">
                    <div class="skills__names">
                        <i class='bx bxl-html5 skills__icon'></i>
                        <span class="skills__name">Python</span>
                    </div>
                    <div class="skills__bar skills__java">

                    </div>
                    <div>
                        <span class="skills__percentage">100%</span>
                    </div>
                </div>
                <div class="skills__data">
                    <div class="skills__names">
                        <i class='bx bxl-css3 skills__icon'></i>
                        <span class="skills__name">Java</span>
                    </div>
                    <div class="skills__bar skills__cplusplus">

                    </div>
                    <div>
                        <span class="skills__percentage">85%</span>
                    </div>
                </div>
                <div class="skills__data">
                    <div class="skills__names">
                        <i class='bx bxl-javascript skills__icon' ></i>
                        <span class="skills__name">HTML/CSS</span>
                    </div>
                    <div class="skills__bar skills__python">

                    </div>
                    <div>
                        <span class="skills__percentage">75%</span>
                    </div>
                </div>
                <div class="skills__data">
                    <div class="skills__names">
                        <i class='bx bxs-paint skills__icon'></i>
                        <span class="skills__name">JavaScript</span>
                    </div>
                    <div class="skills__bar skills__html">

                    </div>
                    <div>
                        <span class="skills__percentage">70%</span>
                    </div>
                </div>
                <div class="skills__data">
                    <div class="skills__names">
                        <i class='bx bxs-paint skills__icon'></i>
                        <span class="skills__name">C++</span>
                    </div>
                    <div class="skills__bar skills__html">

                    </div>
                    <div>
                        <span class="skills__percentage">65%</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

my_website/templates/my_website/work.html
{% extends 'my_website/base.html' %}

{% load static %}

{% block content %}

<main class="l-main">
    <!--===== WORK =====-->
    <section class="work section" id="work">
        <h2 class="section-title">Work</h2>

        <div class="work__container bd-grid">
            {% for project in projects %}
                <div id="gallery" class="work__img">
                    <a href="{% url 'my_website:project_details' project.pk %}">
                        <img src="{% static project.image %}" alt="image thumbnail">
                    </a>
                    <br>
                    <p>{{project.short_description}}</p>
                    <br>
                    <a href="{% url 'my_website:project_details' project.pk %}" class="button">Read more</a>
                </div>
            {% endfor %}
        </div>
    </section>
</main>

{% endblock %}